- name: printing datatypes
  hosts: mongodb
  vars:
  - age: 20 # number
  - isdevops: true # boolean
  - my_string: "Hello, Ansible!"
  - names:
    - rakesh
    - dubbu
    - ram
  - places:
     city: hyd
     vill: gotlur
     country: ind  
  tasks:
  - name: print number variable
    ansible.builtin.debug:
      msg: "{{age}}"
  - name: print String variable
    ansible.builtin.debug:
      msg: "{{my_string}}"
  - name: print Boolean variable
    ansible.builtin.debug:
      msg: "{{isdevops}}"
  - name: print List variable
    ansible.builtin.debug:
      msg: "{{names}}"
  - name: print Map variable
    ansible.builtin.debug:
      msg: "{{places}}"
  