- name: loops in ansible
  hosts: localhost
  become: yes
  tasks:
  - name: Add several users
    ansible.builtin.debug:
     msg: "{{item}}"
    loop:
     - rakesh
     - dubbu

  - name: Install the latest version of Apac
    ansible.builtin.yum:
     name: "{{item.name}}"
     state: "{{item.state}}"
    loop:
     - { name: 'nginx', state: absent }
     - { name: 'postfix', state: absent   }
     - { name: 'cyrus-sasl-plain', state: present }
     - { name: 'mailx', state: present }
     - 