- name: creating loops
  hosts: localhost
  tasks:
  - name: printing loops
    ansible.builtin.debug:
      msg: "{{item}}"
    loop:
      - rakesh
      - dubbu
      - hyd 
  - name: installing nginx and git
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}" 
    loop:
      - { name: 'nginx', state: 'installed' }
      - { name: 'git', state: 'installed' }        

   


       
