- name: loops in ansible
  hosts: localhost
  tasks:
  - name: Add several users
    ansible.builtin.debug:
     msg: "{{item}}"
    loop:
     - rakesh
     - dubbu

  - name: Install the latest version of Apac
    ansible.builtin.yum:
     name: "{{item}}"
     state: present
    loop:
     - nginx
     - postfix 