- name: variable tasks
  hosts: localhost
  vars:
   name: rakesh
   city: hyderabad
  tasks:
  - name: printing nesting
    ansible.builtin.debug:
    vars:
     location: dubai
     hobbies: movies
    ansible.builtin.debug:
     msg: "my name is {{name}} and living in {{city}} and my hobby is watching {{hobbies}}"