- name: variables at play level
  hosts: mongodb
  vars:
    Name: abhi-play
    place: vempalli
    working: hyd
  tasks:
  - name: printing the variables
    ansible.builtin.debug:
      msg: my name is {{Name}}, belongs to {{place}}, working in hyd  


