- name: variables with different files
  hosts: mongodb
  vars:
   NAME: lakshman-play
  vars_files:
   - rakesh.yaml
  vars_prompt:
  - name: NAME
    prompt: enter your username
    private: false 
  tasks:
  - name: printing the variables from task
    vars:
     NAME: lakshman-task
    ansible.builtin.debug:
     msg: "my name is {{NAME}}"     
         