- name: variables with different files
  hosts: localhost
  vars_files:
   - rakesh.yaml
  tasks:
  - name: printing the varaibles from rakesh.yaml
    ansible.builtin.debug:
     msg: "my name is {{NAME}} and living in" 